version: '3'

volumes:
  motley_cue_sock:
  openldap_data:
    driver: local

networks:
  my-network:
    driver: bridge

services:
  ssh_oidc:
    image: ddgu/ssh_oidc:unix
    init: true
    restart: on-failure
    ports:
      - ${PORT_SSH}:22
    environment:
      - UID
      - GID
      - SHELL
    volumes:
      - ${CONFIG_FOLDER}:/config_files
      - motley_cue_sock:/run/motley_cue
    networks:
      - my-network

  nginx:
    image: ddgu/nginx:motley_cue
    restart: on-failure
    hostname: "mc_endpoint"
    ports:
      - ${PORT_MOTLEY_CUE}:8080
    volumes:
      - ${CONFIG_FOLDER}:/config_files
      - motley_cue_sock:/run/motley_cue
    networks:
      - my-network
